# Generated by Django 5.0.1 on 2024-01-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='country',
        ),
    ]
